### ISSUE TITLE
 Could not find an appropriate factory to load ontology from ontology document

### ISSUE THREAD

**Issue by Tomsanm** [ernestojimenezruiz/logmap-matcher#12]
org.semanticweb.owlapi.model.OWLOntologyFactoryNotFoundException: Could not find an appropriate factory to load ontology from ontology document: <E://logmap//a//data//OAEI2018//LargeBioMed_dataset_oaei2012//oaei2012_FMA_small_overlapping_nci.owl>
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1072)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:947)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:903)
	at UsingLogMapMatcher.<init>(UsingLogMapMatcher.java:41)
	at UsingLogMapMatcher.main(UsingLogMapMatcher.java:87)

**Comment by Tomsanm** [comment]
how to resolve

**Comment by ernestojimenezruiz** [comment]
For some reason I was not getting the notifications from the issues.

Nevertheless this seems to be a problem of the format of the input ontology.

Ernesto
