### ISSUE TITLE
Web version different than the standalone ?

### ISSUE THREAD

**Issue by tumblewind** [ernestojimenezruiz/logmap-matcher#16]
Both the below scenarios work perfect with the web version. Finds the match for Dim_patient
http://krrwebtools.cs.ox.ac.uk/logmap/output/matching_07_04_2020__20_47_14_29/mappings.txt

http://hl7.org/fhir/integer|http://watsonhealth.ibm.com/cro/integer|=|0.7|CLS
http://hl7.org/fhir/string|http://watsonhealth.ibm.com/cro/string|=|0.7|CLS
http://hl7.org/fhir/boolean|http://watsonhealth.ibm.com/cro/boolean|=|0.7|CLS
http://hl7.org/fhir/Patient|http://watsonhealth.ibm.com/cro/Dim_Patient|=|0.52|CLS
http://hl7.org/fhir/value|http://watsonhealth.ibm.com/cro/value|=|1.0|DPROP

Standalone (build from Github)
1. with ELK reasoner turned on in parameters.txt I get
Running LogMap Matcher ....
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.semanticweb.owlapi.model.OWLRuntimeException: No current axiom; is the walker being used outside of an ontology visit?
	at org.semanticweb.owlapi.util.OWLOntologyWalkerVisitor.getCurrentAxiom(OWLOntologyWalkerVisitor.java:48)
	at org.semanticweb.owlapi.profiles.OWL2DLProfile$OWL2DLProfileObjectVisitor.visit(OWL2DLProfile.java:477)
	at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.accept(OWLAnnotationPropertyImpl.java:83)
	at org.semanticweb.owlapi.util.OWLObjectWalker.passToVisitor(OWLObjectWalker.java:137)
	at org.semanticweb.owlapi.util.StructureWalker.process(StructureWalker.java:87)
	at org.semanticweb.owlapi.util.StructureWalker.visit(StructureWalker.java:687)
	at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl.accept(OWLAnnotationPropertyImpl.java:83)
	at org.semanticweb.owlapi.profiles.OWLOntologyProfileWalker$1.visit(OWLOntologyProfileWalker.java:56)
	at uk.ac.manchester.cs.owl.owlapi.OWLAnnotationImpl.accept(OWLAnnotationImpl.java:141)
	at org.semanticweb.owlapi.util.StructureWalker.process(StructureWalker.java:101)
	at org.semanticweb.owlapi.util.StructureWalker.visit(StructureWalker.java:116)
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.accept(OWLImmutableOntologyImpl.java:852)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.accept(ConcurrentOWLOntologyImpl.java:396)
	at org.semanticweb.owlapi.util.OWLObjectWalker.walkStructure(OWLObjectWalker.java:181)
	at org.semanticweb.owlapi.profiles.OWL2DLProfile.checkOntology(OWL2DLProfile.java:146)
	at org.semanticweb.owlapi.profiles.OWL2ELProfile.checkOntology(OWL2ELProfile.java:106)
	at uk.ac.ox.krr.logmap2.reasoning.profiles.CheckOWL2Profile.isInOWL2ELProfile(CheckOWL2Profile.java:59)
	at uk.ac.ox.krr.logmap2.indexing.OntologyProcessing.setUpReasoner_ELK(OntologyProcessing.java:2809)
	at uk.ac.ox.krr.logmap2.indexing.OntologyProcessing.setTaxonomicData(OntologyProcessing.java:2625)
	at uk.ac.ox.krr.logmap2.LogMap2Core.IndexLexiconAndStructure(LogMap2Core.java:942)
	at uk.ac.ox.krr.logmap2.LogMap2Core.IndexLexiconAndStructure(LogMap2Core.java:886)
	at uk.ac.ox.krr.logmap2.LogMap2Core.<init>(LogMap2Core.java:421)
	at uk.ac.ox.krr.logmap2.LogMap2Core.<init>(LogMap2Core.java:214)
	at uk.ac.ox.krr.logmap2.LogMap2_Matcher.<init>(LogMap2_Matcher.java:63)
	at uk.ac.ox.krr.logmap2.LogMap2_CommandLine.main(LogMap2_CommandLine.java:106)

2. With HemiT

It just simply ignores the custom datatypes

http://hl7.org/fhir/string|http://watsonhealth.ibm.com/cro/string|=|0.7|CLS
http://hl7.org/fhir/boolean|http://watsonhealth.ibm.com/cro/boolean|=|0.7|CLS
http://hl7.org/fhir/integer|http://watsonhealth.ibm.com/cro/integer|=|0.7|CLS
http://hl7.org/fhir/value|http://watsonhealth.ibm.com/cro/value|=|1.0|DPROP

**Comment by ernestojimenezruiz** [comment]
For some reason I was not getting the notifications from the issues.

The versions are different. The one in the Web service was deployed in 2013 or 2014.

The problem with ELK seems to be a internal problem with the reasoner.

The missing mapping was borderline and may have not passed the cut in the new version depending on the neighborhood information.

Ernesto

**Comment by ernestojimenezruiz** [comment]
Hi 

The issue with ELK has been solved. The problem was actually when checking if the ontology was in the EL profile

Ernesto.
