### ISSUE TITLE
No result and error on standalone version

### ISSUE THREAD

**Issue by kataph** [ernestojimenezruiz/logmap-matcher#41]
Hi, 
I also did not receive the mail with the results. 
Additionally, attempting to run the standalone version gives me the following error:

```
C:\Users\utente\Downloads\logmap-matcher-standalone-july-2021>java -jar logmap-matcher-4.0.jar LITE file:rswo-1.3.0.ttl file:rswo-1.3.0.ttl C://Users/utente/Downloads/logmap-matcher-standalone-july-2021

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/Users/utente/Downloads/logmap-matcher-standalone-july-2021/java-dependencies/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Size LogMap Lite mappings: 111
Time loading ontos (s): 1.895
LogMap Lite Matching Time (s): 0.09200000000000008
java.lang.IllegalArgumentException: URI is not hierarchical
        at java.base/java.io.File.<init>(File.java:420)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.prepareActualOutput(AbstractOWLStorer.java:80)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:63)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1217)
        at uk.ac.ox.krr.logmap2.io.OWLAlignmentFormat.saveOutputFile(OWLAlignmentFormat.java:329)
        at uk.ac.ox.krr.logmap2.io.OutPutFilesManager.closeAndSaveFiles(OutPutFilesManager.java:143)
        at uk.ac.ox.krr.logmap_lite.LogMap_Lite.saveMapping(LogMap_Lite.java:447)
        at uk.ac.ox.krr.logmap_lite.LogMap_Lite.<init>(LogMap_Lite.java:246)
        at uk.ac.ox.krr.logmap2.LogMap2_CommandLine.main(LogMap2_CommandLine.java:124)
```

Any idea about these?
Many thanks

**Comment by proccaserra** [comment]
@kataph I was having related issues but a suggestion in https://github.com/ernestojimenezruiz/logmap-matcher/issues/39 may help (if using java 17 LTS)

**Comment by ernestojimenezruiz** [comment]
Hi @kataph 

Regarding the Web interface, we will soon deploy a new version with the mailing facility fixed (a MSc student has fixed the issues). Google made some changes last year that broke the system.

The error you show is typically related to the paths. Give a look to:
https://code.google.com/archive/p/logmap-matcher/wikis
In windows the output path may need to start with "/". I did not have access to a Windows machine so I know paths in Windows were giving issues.

Ernesto

**Comment by kataph** [comment]
Indeed, the problem was that a "/" had to be added before the absolute path in Windows. I found trace of that also in the old wiki, here: https://code.google.com/archive/p/logmap-matcher/wikis/FAQ.wiki

many thanks
