### ISSUE TITLE
Error processing labels: trying to cast IRI to OWLLiteral

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ernestojimenezruiz/logmap-matcher#6]
```
What steps will reproduce the problem?
Error when matching
1. http://sensormeasurement.appspot.com/naturopathy# 
2. http://kmi.open.ac.uk/projects/smartproducts/ontologies/food_taxonomy.owl 

Error:

java.lang.ClassCastException: org.semanticweb.owlapi.model.IRI$IRIImpl cannot 
be cast to org.semanticweb.owlapi.model.OWLLiteral
        at uk.ac.ox.krr.logmap2.overlapping.OntologyProcessing4Overlapping.extractLabels4OWLCls(OntologyProcessing4Overlapping.java:256)
        at uk.ac.ox.krr.logmap2.overlapping.OntologyProcessing4Overlapping.processOntologyClassLabels(OntologyProcessing4Overlapping.java:134)
        at uk.ac.ox.krr.logmap2.overlapping.LexicalOverlappingExtractor.createOverlapping(LexicalOverlappingExtractor.java:222)
        at uk.ac.ox.krr.logmap2.overlapping.LexicalOverlappingExtractor.createOverlapping(LexicalOverlappingExtractor.java:147)
        at uk.ac.ox.krr.logmap2.web_service.LogMap_WebService.OverlappingEstimation(LogMap_WebService.java:301)
        at uk.ac.ox.krr.logmap2.web_service.LogMap_WebService.<init>(LogMap_WebService.java:137)
        at uk.ac.ox.krr.logmap2.web_service.LogMapRequest$LogMapThread.run(LogMapRequest.java:652)
        at java.lang.Thread.run(Thread.java:722)

```

Original issue reported on code.google.com by `ernesto....@gmail.com` on 5 Sep 2013 at 4:43

**Comment by ernestojimenezruiz** [comment]
Solved in standalone version.
